# Build settings for API (NestJS)
[build]
  # Base directory is repository root (default)
  # Package directory is set in Netlify UI to: apps/api
  command = "npm run build"
  publish = "apps/api/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "11.6.2"

# Context-specific build settings
[context.production]
  command = "npm run build"

# Ignore builds if no changes in relevant directories
[build.ignore]
  command = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- apps/api packages package.json"

# Functions configuration (if using Netlify Functions)
[functions]
  directory = "dist"
  node_bundler = "esbuild"

# Environment variables (set in Netlify UI)
# NODE_ENV=production
# DATABASE_URL
# JWT_SECRET
